# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 10:39
from __future__ import unicode_literals

import carrier.enums
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0002_recipient_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='preferred_transport',
            field=enumfields.fields.EnumField(blank=True, enum=carrier.enums.TransportType, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='transport',
            field=enumfields.fields.EnumField(blank=True, enum=carrier.enums.TransportType, max_length=100, null=True),
        ),
    ]
