# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0003_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pushbullet_access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrier.Contact'),
        ),
    ]
