# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0004_pushbullet_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
